/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Window.java
 *
 * Created on 07.12.2011, 19:22:29
 */
package se.edu.gui.aufgabe06;

import javax.swing.JOptionPane;

/**
 *
 * @author steeb
 */
public class Window extends javax.swing.JFrame {

    /** Creates new form Window */
    public Window() {
        initComponents();
        this.setDefaultCloseOperation(Window.EXIT_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mDatei = new javax.swing.JMenu();
        mDateiBeenden = new javax.swing.JMenuItem();
        mBearbeiten = new javax.swing.JMenu();
        mBearbeitenKunden = new javax.swing.JMenu();
        mBearbeitenKundenAufnehmen = new javax.swing.JMenuItem();
        mBearbeitenKundenAendern = new javax.swing.JMenuItem();
        mBearbeitenKundenLoeschen = new javax.swing.JMenuItem();
        mBearbeitenWein = new javax.swing.JMenu();
        mBearbeitenWeinAufnehmen = new javax.swing.JMenuItem();
        mBearbeitenWeinAendern = new javax.swing.JMenuItem();
        mBearbeitenWeinLoeschen = new javax.swing.JMenuItem();
        mHilfe = new javax.swing.JMenu();
        mHilfeInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mDatei.setText("Datei");

        mDateiBeenden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mDateiBeenden.setText("Beenden");
        mDateiBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDateiBeendenActionPerformed(evt);
            }
        });
        mDatei.add(mDateiBeenden);

        menuBar.add(mDatei);

        mBearbeiten.setText("Bearbeiten");

        mBearbeitenKunden.setText("Kunden");

        mBearbeitenKundenAufnehmen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mBearbeitenKundenAufnehmen.setText("Aufnehmen");
        mBearbeitenKunden.add(mBearbeitenKundenAufnehmen);

        mBearbeitenKundenAendern.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mBearbeitenKundenAendern.setText("Ändern");
        mBearbeitenKunden.add(mBearbeitenKundenAendern);

        mBearbeitenKundenLoeschen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mBearbeitenKundenLoeschen.setText("Löschen");
        mBearbeitenKunden.add(mBearbeitenKundenLoeschen);

        mBearbeiten.add(mBearbeitenKunden);

        mBearbeitenWein.setText("Wein");

        mBearbeitenWeinAufnehmen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mBearbeitenWeinAufnehmen.setText("Aufnehmen");
        mBearbeitenWein.add(mBearbeitenWeinAufnehmen);

        mBearbeitenWeinAendern.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mBearbeitenWeinAendern.setText("Ändern");
        mBearbeitenWein.add(mBearbeitenWeinAendern);

        mBearbeitenWeinLoeschen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mBearbeitenWeinLoeschen.setText("Löschen");
        mBearbeitenWein.add(mBearbeitenWeinLoeschen);

        mBearbeiten.add(mBearbeitenWein);

        menuBar.add(mBearbeiten);

        mHilfe.setText("?");

        mHilfeInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mHilfeInfo.setText("Info");
        mHilfeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHilfeInfoActionPerformed(evt);
            }
        });
        mHilfe.add(mHilfeInfo);

        menuBar.add(mHilfe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mDateiBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDateiBeendenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mDateiBeendenActionPerformed

    private void mHilfeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHilfeInfoActionPerformed
        JOptionPane.showMessageDialog(this, "Info text ...", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mHilfeInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mBearbeiten;
    private javax.swing.JMenu mBearbeitenKunden;
    private javax.swing.JMenuItem mBearbeitenKundenAendern;
    private javax.swing.JMenuItem mBearbeitenKundenAufnehmen;
    private javax.swing.JMenuItem mBearbeitenKundenLoeschen;
    private javax.swing.JMenu mBearbeitenWein;
    private javax.swing.JMenuItem mBearbeitenWeinAendern;
    private javax.swing.JMenuItem mBearbeitenWeinAufnehmen;
    private javax.swing.JMenuItem mBearbeitenWeinLoeschen;
    private javax.swing.JMenu mDatei;
    private javax.swing.JMenuItem mDateiBeenden;
    private javax.swing.JMenu mHilfe;
    private javax.swing.JMenuItem mHilfeInfo;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
