/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreisumrechnerPanel.java
 *
 * Created on 28.12.2011, 16:10:09
 */
package se.edu.gui.aufgabe04;

import java.awt.event.ItemEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author steeb
 */
public class PreisumrechnerPanel extends javax.swing.JPanel {
    
    private enum Richtung {
        NACH_UNTEN,
        NACH_OBEN
    }
    
    private Richtung richtung;

    /** Creates new form PreisumrechnerPanel */
    public PreisumrechnerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelPreisUmrechner = new javax.swing.JPanel();
        lblFlaschengroesse = new javax.swing.JLabel();
        lblFlaschenpreis = new javax.swing.JLabel();
        lblPreisProL = new javax.swing.JLabel();
        cbFlaschengroesse = new javax.swing.JComboBox();
        btnUmrechnenDown = new javax.swing.JButton();
        btnUmrechnenUp = new javax.swing.JButton();
        lblEuro0 = new javax.swing.JLabel();
        lblEuro1 = new javax.swing.JLabel();
        tfFlaschenpreis = new javax.swing.JTextField();
        tfPreisProL = new javax.swing.JTextField();

        PanelPreisUmrechner.setLayout(new java.awt.GridBagLayout());

        lblFlaschengroesse.setText("Flaschengröße:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(lblFlaschengroesse, gridBagConstraints);

        lblFlaschenpreis.setText("Flaschenpreis:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(lblFlaschenpreis, gridBagConstraints);

        lblPreisProL.setText("Preis pro L:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(lblPreisProL, gridBagConstraints);

        cbFlaschengroesse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0,187l", "0,25l", "0,375l", "0,5l", "0,62l", "0,75l", "0,8l", "1l", "1,5l" }));
        cbFlaschengroesse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFlaschengroesseItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(cbFlaschengroesse, gridBagConstraints);

        btnUmrechnenDown.setText("↓");
        btnUmrechnenDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmrechnenDownActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(btnUmrechnenDown, gridBagConstraints);

        btnUmrechnenUp.setText("↑");
        btnUmrechnenUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmrechnenUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(btnUmrechnenUp, gridBagConstraints);

        lblEuro0.setText("€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        PanelPreisUmrechner.add(lblEuro0, gridBagConstraints);

        lblEuro1.setText("€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        PanelPreisUmrechner.add(lblEuro1, gridBagConstraints);

        tfFlaschenpreis.setDocument(new PreisDocument());
        tfFlaschenpreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfFlaschenpreis.getDocument().addDocumentListener(new ChangeListener());
        tfFlaschenpreis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFlaschenpreistextfieldMarkAll(evt);
            }
        });
        tfFlaschenpreis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFlaschenpreisbeep(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(tfFlaschenpreis, gridBagConstraints);

        tfPreisProL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPreisProL.setInputVerifier(new PreisVerifier());
        tfPreisProL.getDocument().addDocumentListener(new ChangeListener());
        tfPreisProL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPreisProLtextfieldMarkAll(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPreisUmrechner.add(tfPreisProL, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPreisUmrechner, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPreisUmrechner, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbFlaschengroesseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFlaschengroesseItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {             if (!tfFlaschenpreis.getText().equals("") && !tfPreisProL.getText().equals("")) {                 if (richtung == Richtung.NACH_OBEN) {                     btnUmrechnenUpActionPerformed(null);                 } else {                     btnUmrechnenDownActionPerformed(null);                 }             }         }     }//GEN-LAST:event_cbFlaschengroesseItemStateChanged

    private void btnUmrechnenDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmrechnenDownActionPerformed

        NumberFormat nf = NumberFormat.getNumberInstance();         double flaschenpreis;         double flaschengroeße;         try {             flaschenpreis = nf.parse(tfFlaschenpreis.getText()).doubleValue();             flaschengroeße = nf.parse(cbFlaschengroesse.getItemAt(cbFlaschengroesse.getSelectedIndex()).toString()).doubleValue();             tfPreisProL.setText(new DecimalFormat("#.00").format(1 / flaschengroeße * flaschenpreis));         } catch (ParseException ex) {             JOptionPane.showMessageDialog(this, "Falsche Format", "Bitte deutsches Wärhungsformat einhalten", JOptionPane.ERROR_MESSAGE);         }         richtung = Richtung.NACH_UNTEN;     }//GEN-LAST:event_btnUmrechnenDownActionPerformed

    private void btnUmrechnenUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmrechnenUpActionPerformed

        NumberFormat nf = NumberFormat.getNumberInstance();         double preisprol;         double flaschengroeße;         try {             flaschengroeße = nf.parse(cbFlaschengroesse.getItemAt(cbFlaschengroesse.getSelectedIndex()).toString()).doubleValue();             preisprol = nf.parse(tfPreisProL.getText()).doubleValue();             tfFlaschenpreis.setText(new DecimalFormat("#.00").format(flaschengroeße * preisprol));         } catch (ParseException ex) {             JOptionPane.showMessageDialog(this, "Falsche Format", "Bitte deutsches Wärhungsformat einhalten", JOptionPane.ERROR_MESSAGE);         }         richtung = Richtung.NACH_UNTEN;     }//GEN-LAST:event_btnUmrechnenUpActionPerformed

    private void tfFlaschenpreistextfieldMarkAll(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFlaschenpreistextfieldMarkAll

        ((JTextField) evt.getComponent()).selectAll();     }//GEN-LAST:event_tfFlaschenpreistextfieldMarkAll

    private void tfFlaschenpreisbeep(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFlaschenpreisbeep

        if (!(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar() == ',')) {             java.awt.Toolkit.getDefaultToolkit().beep();             System.out.println("beep");         }     }//GEN-LAST:event_tfFlaschenpreisbeep

    private void tfPreisProLtextfieldMarkAll(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPreisProLtextfieldMarkAll

        ((JTextField) evt.getComponent()).selectAll();     }//GEN-LAST:event_tfPreisProLtextfieldMarkAll

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPreisUmrechner;
    private javax.swing.JButton btnUmrechnenDown;
    private javax.swing.JButton btnUmrechnenUp;
    private javax.swing.JComboBox cbFlaschengroesse;
    private javax.swing.JLabel lblEuro0;
    private javax.swing.JLabel lblEuro1;
    private javax.swing.JLabel lblFlaschengroesse;
    private javax.swing.JLabel lblFlaschenpreis;
    private javax.swing.JLabel lblPreisProL;
    private javax.swing.JTextField tfFlaschenpreis;
    private javax.swing.JTextField tfPreisProL;
    // End of variables declaration//GEN-END:variables


        class ChangeListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent de) {
            cleanOtherField(de);
        }

        @Override
        public void removeUpdate(DocumentEvent de) {
            cleanOtherField(de);
        }

        @Override
        public void changedUpdate(DocumentEvent de) {  
        }
        
        private void cleanOtherField(DocumentEvent de) {
            if (tfFlaschenpreis.hasFocus())
                tfPreisProL.setText("");
            else if (tfPreisProL.hasFocus())
                tfFlaschenpreis.setText("");
        }
        
    }
    
}
